### PR TITLE
Add travis & homu config

### PR DESCRIPTION
**Pull request by omgdlight**

### CODE REVIEW

**Comment by omgdlight** [comment]
@homuhomuchan r+

**Comment by omgdlight** [comment]
@homuhomuchan r+

**Comment by omgdlight** [comment]
@homuhomuchan r+

**Comment by omgdlight** [comment]
@homuhomuchan r+

**Comment by homuhomuchan** [comment]
:pushpin: Commit 964c11a has been approved by `omgdlight`

**Comment by homuhomuchan** [comment]
:hourglass: Testing commit 964c11a with merge 2fc5c30...

**Comment by omgdlight** [comment]
@homuhomuchan retry

**Comment by homuhomuchan** [comment]
:hourglass: Testing commit 964c11a with merge 370d7b9...

**Pull request merged**
